### PR TITLE
make sure script terminates on any failure

### PR DESCRIPTION
**Pull request by smuzaffar**
please do not merge it yet. I would like to test it using jenkins first

### CODE REVIEW

**Comment by smuzaffar** [comment]
ping cmsbot

**Comment by smuzaffar** [comment]
please test

**Comment by degrutto** [comment]
sorry for the naive question, where can I see the test failed?

**Comment by smuzaffar** [comment]
I have updated the cmsbot to post a link in the comment for the build logs. Now cmsbot should also upload all the contents of CMSSW_*/src (without .root files) to a web server.

**Comment by smuzaffar** [comment]
@degrutto , look like full chain of test is now working. Please merge this PR to get steps.sh working properly.

Currently it takes 3 hours to run this test. I noticed that you run two cmsRun job here in serial. Both if these are independent jobs, so to save some time you can run them in parallel (in separate directories, as they generate some type of files)

**Comment by degrutto** [comment]
@smuzaffar thanks so much. Yes we will now improve the script based on what is there, and the fact we have a working example!thanks a lot

Can you please clarify how to trigger the test?
1. Making a PR and then writing a comment "please test" will run script.sh ? correct ?

**Comment by smuzaffar** [comment]
@degrutto , yes make a PR and commenting "please test" should start the tests. These are the cmsbot commands which one can use https://github.com/cms-sw/cms-sw.github.io/blob/master/cms-bot-cmssw-cmds.md . I shall update these for non-cmssw repos. Right now most of these should work (e.g. "please test", "abort test" etc.)

List of user who can trigger the tests are
https://github.com/cms-sw/cms-bot/blob/master/repos/EcalLaserValidation/HLT_EcalLaserValidation/categories.py#L9
and CMSSW_L2's which are mentioned here
https://github.com/cms-sw/cms-bot/blob/master/repos/EcalLaserValidation/HLT_EcalLaserValidation/categories.py#L22

If you need more github users to trigger tests then please make a PR for https://github.com/cms-sw/cms-bot/blob/master/repos/EcalLaserValidation/HLT_EcalLaserValidation/categories.py

**Pull request merged**
